baseURL = 'https://kutsuyayuki.github.io/'
languageCode = 'en-us'
Title = 'Yukis website'

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "projects"
    name = "projects"
    url = "/projects"
    weight = 2
    [[menu.main]]
    identifier = "notes"
    name = "Notes"
    url = "/notes/"
    weight = 3
  [[menu.main]]
    identifier = "about"
    name = "About Us"
    url = "/about/"
    weight = 4
    
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true